### ISSUE TITLE
TS mask Prop

### ISSUE THREAD

**Issue by feliperramos** [studiojms/react-mask-input#1]
Hi! I have used your component in my project and found an issue when use your component in Typescript!

In the mask prop you have to add an array `string[]` too, because in the example in Github Page has an Array string:

```
<MaskInput
  type="text"
  mask={['(99) 9999-9999', '(99) 9 9999-9999']}
  placeholder="Phone number"
/>
```

```
interface MaskInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
    mask: string | string[]; <--- // I change here and fix the TS warning
}
```

adding a string[] fix the Typescript Error in my project, but i think you can do it in the project too. Thanks!

**Comment by studiojms** [comment]
@feliperramos a versão 1.0.1 já está publicada no npm com as alterações sugeridas. Obrigado por contribuir com este projeto!

https://www.npmjs.com/package/react-awesome-mask-input
